export const GET_MOVIES_START = 'GET_MOVIES_START'; 
export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS'; 
export const GET_MOVIES_FAILURE = 'GET_MOVIES_FAILURE';

export const UPDATE_MOVIES_START = 'UPDATE_MOVIES_START'; 
export const UPDATE_MOVIES_SUCCESS = 'UPDATE_MOVIES_SUCCESS'; 
export const UPDATE_MOVIES_FAILURE = 'UPDATE_MOVIES_FAILURE'; 

export const DELETE_MOVIES_START = 'DELETE_MOVIES_START'; 
export const DELETE_MOVIES_SUCCESS = 'DELETE_MOVIES_SUCCESS'; 
export const DELETE_MOVIES_FAILURE = 'DELETE_MOVIES_FAILURE'; 